10 routing wishlist
balashovmb/tn-react pull request #21
Opened 2020-09-16 10:56 UTC by balashovmb

2020-09-16 13:20 UTC, index01d requested changes

2020-09-16 13:20 UTC, index01d commented on src/Book/Wishlist.js
> +  const wishlist = localStorage.getItem('wishlist').split(',').filter(Boolean) || [];
нужно получать данные из контекста. Лучше избегать прямых обращений к ls в компонентах ниже по иерархии

2020-09-16 13:20 UTC, index01d commented on src/Book/WishlistProvider.js
> +      const wishlist = localStorage.getItem('wishlist').split(',').filter(Boolean);
Также следует использовать контекст

2020-09-21 09:24 UTC, index01d approved these changes

2020-09-21 09:24 UTC, index01d commented on src/Book/AddToWishlistButton.js
> +  const [itemInWishlist, setItemInWishlist] = useState(Boolean(wishlist[book.Id]));
1) вероятно можно было написать !!wishlist[book.Id]
2) Почему бы не реализовать метод проверки наличия книги в вишлисте в провайдере контекста? Тогда его можно будет реиспользовать, а ниже не придётся обрабатывать состояние

2020-09-21 09:24 UTC, index01d commented on src/Book/AddToWishlistButton.js
> +  const { wishlist, toggleWishlistItem } = useContext(WishlistContext);
думаю лучше было бы получить `isWishedBook` здесь

2020-09-21 10:33 UTC, balashovmb commented on src/Book/AddToWishlistButton.js
> +  const [itemInWishlist, setItemInWishlist] = useState(Boolean(wishlist[book.Id]));
Спасибо, так лаконичнее! Только без состояния не перерисовывается кнопка после клика

2020-09-21 12:15 UTC, merged